config/routes.rb
Rails.application.routes.draw do  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/:Word' => 'dictionaries#index', via: [:get, :post]
  match '/' => 'dictionaries#index', via: [:get, :post]
  get '/dictionary/sitemap' => 'dictionaries#sitemap'
  resources :dictionaries, except: [:new,:edit,:create,:update,:delete] do
    get :autocomplete_dictionary_word, :on => :collection
  end
  root 'dictionaries#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
	max_paginates_per 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
	autocomplete :dictionary, :word
	def index
		@word_field=params[:Word]
		if !@word_field.blank?	
			@word_field=@word_field.gsub(/-/,' ')
			t = Dictionary.arel_table
			@word= Dictionary.where(t[:Word].matches(@word_field)).first
			@synonyms=@word.synonyms.split(",") if !@word.nil?
			@antonyms=@word.antonyms.split(",") if !@word.nil?
		end
		@word_day = Dictionary.all.sample(30)
	end	

	def sitemap
		@words = Dictionary.order(:Word).page(params[:page]).per(100)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default panel-search">
      <div class="panel-heading">
          <div class="row">
            <%= form_tag('', :id => "search-form", :class => 'form-horizontal', :multipart => true, method: :post) do %>  
              <div class="form-group search-group">
                <div class="col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-md-2 col-sm-2 col-xs-2 text-right">
                  <label class="label-control search-label"><strong>தேடல்:</strong></label>
                </div>    
                <div class="col-md-7 col-sm-7 col-xs-7">
                  <%= autocomplete_field_tag :Word, params[:Word], autocomplete_dictionary_word_dictionaries_path, :id => "word", :class => 'form-control', :placeholder => 'சொற்களை ', :required => true %>
                </div>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div> 

<% if !@word.nil? %>
  <div class="row">
      <h1>
        <div class="col-md-12">
          <%= @word.Word %>
        </div>
      </h1>
      <div class="col-md-12 col-xs-6 col-sm-6">
        <small class="text-muted"> [<%= @word.related_to %>]</small>
      </div> 
  </div>
  <hr>

  <div class="row">
    <div class="col-md-8">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2>
              Synonyms
            </h2>
            <hr>
            <div class="row">
              <% @synonyms.each do |synonym| %>
                <div class="col-md-3 col-sm-3 col-xs-6">
                  <%= link_to synonym, "/#{synonym}", :class => 'btn btn-block btn-default btn-word' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2>
              Antonyms
            </h2>
            <hr>
            <div class="row">
              <% @antonyms.each do |antonym| %>
                <div class="col-md-3 col-sm-3 col-xs-6">
                  <%= link_to antonym, "/#{antonym}", :class => 'btn btn-block btn-default btn-word' %>
                </div>
              <% end %>
            </div>   
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
             Word Origin And History
          </h3>
          <hr>
          <p class="origin">
              <%= @word.origin %>
          </p>
        </div>
      </div>
    </div>  
            
  </div>

<% elsif @word_field %>  
  <div class="row blank-row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="text-center text-muted">
            மன்னிக்கவும் கண்டறிய இயலவில்லை
          </h2>
        </div>
      </div>      
  </div>
<% else %>
  <div class="row blank-row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="text-center text-muted">
               சொல்லின் பொருள்,மூலம் கண்டறிய தட்டச்சவும்
            </h2>
          </div>
        </div>
      </div>
  </div>    
<% end %>

  <div class="row blank-row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="row">
              <h3 class="text-center text-muted">
                இன்றைய சொற்கள்
              </h3>
              <hr>
            </div>
            <div class="row">
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <% for i in 0..9 %>
                      <div class="col-md-12 col-sm-12 col-xs-12">
                        <%= link_to @word_day[i].Word, "/#{@word_day[i].Word}", :class => 'btn btn-block btn-default btn-word' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <% for i in 10..19 %>
                      <div class="col-md-12 col-sm-12 col-xs-12">
                        <%= link_to @word_day[i].Word, "/#{@word_day[i].Word}", :class => 'btn btn-block btn-default btn-word' %>
                      </div>
                    <% end %>  
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <% for i in 20..29 %>
                      <div class="col-md-12 col-sm-12 col-xs-12">
                        <%= link_to @word_day[i].Word, "/#{@word_day[i].Word}", :class => 'btn btn-block btn-default btn-word' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>  
  </div>    

app/views/dictionaries/sitemap.html.erb
<div class="row">
      <div class="page-header">
        <h1>SiteMap</h1>
      </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>
            Pages
          </h2>
          <hr>
          <div class="row">
        	<ul>
        		<li>
        			<a href="/">Home</a>
        		</li>
        		<li>
        			<a href="dictionary/sitemap">SiteMap</a>
        		</li>
        	</ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>
            Table Of Contents
          </h2>
          <hr>
          <div class="row">
          	<ul>
          		<% @words.each do |word|%>	
          			<li><%= link_to word.Word, "/#{word.Word}", :class => 'btn-word' %></li>
          		<% end %>	
          	</ul>            	 
          </div>   
        </div>
      </div>
    </div>
    <div class="col-md-12"><%= paginate @words %></div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	
	<% if @word.nil? %>
		<title>அகராதி - தமிழ் சொல் அறிக</title>
	<% else %>
		<title>அகராதி - <%= @word.Word %></title>
	<% end %>	
	
	<meta name="generator" content="Bootply" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta property="og:locale" content="en_US" />
	<meta property="og:site_name" content="SynonymsDir" />

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,400italic,700" rel="stylesheet" type="text/css">
  	<%= javascript_include_tag 'application' %>
  	
  	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-static-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand site-header" href="/">தமிழ் அகராதி</a>
	    </div>
	    <div class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <li class="<%= 'active' if current_page?(root_path) %>"><a href="/">முகப்பு</a></li>
	        <li class="<%= 'active' if current_page?(dictionary_sitemap_path) %>"><a href="/dictionary/sitemap">அனைத்தும்</a></li>
	      </ul>
	    </div><!--/.nav-collapse -->
	  </div>
	</div>

	<div id="wrap">
		<div id="main" class="container">
		  <%= yield %>
		</div>
		<!-- /.container -->
	</div>

	<footer>
	  <div class="container">
	    <div class="row footer-row">
	      <div class="col-md-12">
	        <p class="text-center text-muted">
	          &#169; 2017 Copyrights @navinspm. All Rights Reserved.      
	        </p>
	      </div>
	    </div>
	  </div>
	</footer>
</body>
</html>